name: 'Eslint Action'
description: 'Run eslint and report the results inline'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  eslint-lib:
    required: true
    description: 'Path to your eslint library, probably node_modules/eslint'
  custom-working-directory:
    required: false
    description: 'Path to your working directory, uses `.` if not provided'
  check-run-subtitle:
    required: false
    description: 'A subtitle to add to the check run when annotations are passed back to avoid overwriting each other'
  base-ref:
    required: true
    description: 'The base ref of the pull-request'
branding:
  icon: check-circle
  color: red
