name: 'Eslint Action'
description: 'Run eslint and report the results inline'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  eslint-lib:
    required: true
    description: 'Path to your eslint library, probably node_modules/eslint'
  check-run:
    required: false
    description: 'A sub-name to add to the check run when annotations are passed back'
branding:
  icon: check-circle
  color: red
