
setup:
  checkout:
  - uses: actions/checkout@v2
    name: get the repo
  - uses: actions/checkout@v2
    name: get the base ref
    with:
      ref: '${{ github.base_ref }}'
  yarn:
    setup: checkout
    steps:
      - run: yarn
  changed-files:
    steps:
      - name: Get All Changed Files
        uses: jaredly/get-changed-files@696e6f79663205e7f00ff5856e87d59c03160982
        id: changed
        with:
          format: 'json'
          absolute: true

      - uses: allenevans/set-env@v2.0.0
        with:
          ALL_CHANGED_FILES_DISABLED: '${{ steps.changed.outputs.added_modified }}'
