
setup:
  checkout:
  - uses: actions/checkout@v1
    name: get the repo
  yarn:
    setup: checkout
    steps:
      - run: yarn
  changed-files:
    steps:
      - name: Get All Changed Files
        uses: jitterbit/get-changed-files@v1
        id: changed
        with:
          format: 'json'
      
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          ALL_CHANGED_FILES: '${{ steps.changed.outputs.added_modified }}'
          ALL_CHANGED_FILES_BASE: '${{ github.workspace }}'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Debug
        run: |
          echo The files that were changed: ${ALL_CHANGED_FILES}
          echo The base directory for those files: ${ALL_CHANGED_FILES_BASE}
