
setup:
  checkout:
  - uses: actions/checkout@v1
    name: get the repo
  yarn:
    setup: checkout
    steps:
      - run: yarn
  changed-files:
    steps:
      - name: Get All Changed Files
        uses: jaredly/get-changed-files@absolute
        id: changed
        with:
          format: 'json'
          absolute: true

      - uses: allenevans/set-env@v2.0.0
        with:
          ALL_CHANGED_FILES: '${{ steps.changed.outputs.added_modified }}'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Debug
        run: |
          echo The files that were changed: ${ALL_CHANGED_FILES}
