
setup:
  checkout:
  - uses: actions/checkout@v2
  yarn:
    setup: checkout
    steps:
      - run: yarn
  
  # This gets the list of files that changed in the current pull-request
  # and puts then onto the ALL_CHANGED_FILES env variable, which several
  # of our actions will use.
  changed-files:
    steps:
      - name: Get All Changed Files
        uses: jaredly/get-changed-files@v1.0.1
        id: changed
        with:
          format: 'json' # robust to filenames with spaces
          absolute: true # our tooling expects absolute paths

      # Now we put it on the environment so that it can be picked up by
      # anything that uses actions-utils (e.g. eslint-action, jest-action, etc.)
      - uses: allenevans/set-env@v2.0.0
        with:
          ALL_CHANGED_FILES: '${{ steps.changed.outputs.added_modified }}'
