name: Lint and Unit test
'on':
  - pull_request

include:
  - _setup.yml

jobs:
  lint_and_unit:
    runs-on: ubuntu-latest
    steps:
      - uses: Khan/eslint-action@master
        setup: yarn
        with:
          eslint-lib: ./node_modules/eslint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Khan/flow-coverage-action@master
        setup: yarn
        with: 
          flow-bin: ./node_modules/.bin/flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Khan/jest-action@master
        setup: yarn
        with: 
          jest-bin: ./node_modules/.bin/jest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn flow --color always --quiet
        setup: yarn
