name: Lint and Unit Test
'on':
  - pull_request

include:
  - _setup.yml

jobs:
  lint_and_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Run eslint
        uses: Khan/eslint-action@main
        setup: yarn
        with:
          eslint-lib: ./node_modules/eslint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run jest tests
        uses: Khan/jest-action@main
        setup: yarn
        with:
          jest-bin: ./node_modules/.bin/jest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run jest coverage
        uses: Khan/jest-coverage-action@main
        setup: yarn
        with:
          jest-bin: ./node_modules/.bin/jest
          coverage-data-path: ./coverage/coverage-final.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flow
        uses: Khan/flow-action@main
        setup: yarn
        with:
          flow-bin: ./node_modules/.bin/flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flow coverage
        uses: Khan/flow-coverage-action@main
        setup: yarn
        with:
          flow-bin: ./node_modules/.bin/flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
